spring:
  application:
    name: authorization-service
  datasource:
    url: jdbc:h2:file:./orders
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   
  jackson:
    time-zone: America/El_Salvador
    locale: es_SV
    
server:
  port: 9081
  servlet:
    context-path: /api/v1/demo
  error:
    include-stacktrace: never
    
    
#logging:
#  level:
#    root: INFO
#    '[org.springframework.web]': INFO
#    '[org.springframework.security]': INFO
#    '[org.springframework.oauth2]': INFO
    

    
#--- CONSTANT --
app:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
  constants:
    api:
      consumer:
        local-products-service: http://localhost:9081${server.servlet.context-path}/products
      authroot-url: "/auth"
      auth-url: "/auth/**"
      root-path: "/api/**"
      secured-path: /shop/**
    messages:
      notfound: '%s not found.'
