spring:
  application:
    name: payment-service
  sql:
    init:
      continue-on-error: true
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: ${POSTGRES_PASSWORD:db-pgreSQL22}
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[enable_lazy_load_no_trans]': true
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   
  jackson:
    time-zone: America/El_Salvador
    locale: es_SV
    
server:
  port: 9085
  servlet:
    context-path: /api/v1/demo
  error:
    include-stacktrace: never
    
    
#logging:
#  level:
#    root: INFO
#    '[org.springframework.web]': INFO
#    '[org.springframework.security]': INFO
#    '[org.springframework.oauth2]': INFO
    

    
#--- CONSTANT --
app:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
  constants:
    api:
      consumer:
        local-orderdetails-service: http://localhost:9086/api/v1/demo/order-details
        local-payment-service: http://localhost:9085/api/v1/demo/payments
        local-products-service: http://localhost:9081/api/v1/demo/products
